name: CI

on:
  push:
  pull_request:
      branches: [master]
jobs:
  build-mac:
    runs-on: macos-11
    strategy:
      matrix:
        kernel: [ish, linux]
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: true
      - name: Install dependencies
        run: |
          brew install llvm ninja libarchive
          pip3 install meson
      - name: Clone Linux
        if: matrix.kernel == 'linux'
        run: deps/clone-linux.sh
      - name: Build
        if: matrix.kernel == 'ish'
        run: | 
          xcodebuild -project iSH.xcodeproj -scheme iSH -derivedDataPath "/Users/runner/work/ish-tccd/build/DerivedDataApp" -configuration Release -arch arm64 -sdk iphoneos CODE_SIGNING_ALLOWED=NO
          mkdir Payload
          cp -r build/DerivedDataApp/Build/Products/Release-iphoneos/iSH.app Payload/
          zip -vr iSH-tccd.ipa Payload
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: iSH-tccd
          path: iSH-tccd.ipa
